AllCops:
 DisplayCopNames: true

Metrics/LineLength:
 Enabled: false

Metrics/ModuleLength:
 Enabled: false

Metrics/MethodLength:
 Enabled: false

# TODO
Metrics/CyclomaticComplexity:
 Enabled: false

# The case
Metrics/PerceivedComplexity:
 Enabled: false

# bot_spec
Metrics/BlockLength:
 Enabled: false

# System icons
Layout/IndentHeredoc:
 Enabled: false

# Lingo, horoscopo, wikipedia, date and Stock
Metrics/AbcSize:
 Enabled: false
